name: Reusable Deploy Workflow
on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      service_name:
        required: true
        type: string
      service_version:
        required: true
        type: string
    secrets:
      GH_ACTIONS_PAT:
        required: true

jobs:
  critical-path-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Test Environment
        run: |
          case "${{ inputs.environment_name }}" in
            test) TEST_ENV="test" ;;
            prod) TEST_ENV="uat" ;;   # Run prod tests on UAT
            uat)  TEST_ENV="test" ;;  # Run UAT tests on test
            sb)   TEST_ENV="test" ;;  # Run SB tests on test
            *)    TEST_ENV="test" ;;  # Default fallback
          esac
          echo "TEST_ENV=$TEST_ENV" >> $GITHUB_ENV

      - name: Run Critical Path Tests
        run: |
          echo "Running critical path tests for ${{ inputs.service_name }}"
          echo "Testing in: $TEST_ENV environment"
          sleep 10
          # Uncomment to simulate failure
          # exit 1
          echo "Tests completed successfully"

  deploy:
    needs: [critical-path-tests]
    if: ${{ inputs.service_name != 'cerbos' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    concurrency: '${{ inputs.environment_name }}-${{ inputs.service_name }}'
    outputs:
      needs_testing: ${{ steps.check_test.outputs.needs_testing }}
    steps:
      - name: Check if testing needed
        id: check_test
        run: |
          if [[ "${{ inputs.service_name }}" != "router-api" ]]; then
            echo "needs_testing=true" >> $GITHUB_OUTPUT
          else
            echo "needs_testing=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy Service
        run: |
          echo "Starting deployment of ${{ inputs.service_name }}"
          echo "Version: ${{ inputs.service_version }}"
          echo "Environment: ${{ inputs.environment_name }}"
          sleep 5
          echo "Deployment completed"

