name: Reusable Deploy Workflow
on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      app_version:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: ${{ inputs.environment_name == 'uat' || inputs.environment_name == 'prod' }}
    steps:
      - name: Run Tests
        run: |
          echo "Running tests for ${{ inputs.environment_name }}"
          # Simulate tests
          sleep 10
          # Uncomment to test failure scenario
          # exit 1

  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    if: |
      success() &&
      (
        (inputs.environment_name == 'uat' || inputs.environment_name == 'prod') &&
        needs.run-tests.result == 'success' ||
        (inputs.environment_name != 'uat' && inputs.environment_name != 'prod')
      )
    steps:
      - name: Deploy
        run: |
          echo "Deploying version ${{ inputs.app_version }} to ${{ inputs.environment_name }}"
          # Simulate deployment
          sleep 5
