name: Main Build and Deploy
on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Target Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - uat
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Set Version
        id: set-version
        run: echo "version=1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

  deploy-to-dev:
    needs: build
    if: inputs.deploy_env == 'dev'
    uses: ./.github/workflows/deploy.yml
    with:
      environment_name: dev
      app_version: ${{ needs.build.outputs.app_version }}

  deploy-to-test:
    needs: [build, deploy-to-dev]
    if: inputs.deploy_env == 'test'
    uses: ./.github/workflows/deploy.yml
    with:
      environment_name: test
      app_version: ${{ needs.build.outputs.app_version }}

  deploy-to-uat:
    needs: [build, deploy-to-test]
    if: inputs.deploy_env == 'uat'
    uses: ./.github/workflows/deploy.yml
    with:
      environment_name: uat
      app_version: ${{ needs.build.outputs.app_version }}

  deploy-to-prod:
    needs: [build, deploy-to-uat]
    if: inputs.deploy_env == 'prod'
    uses: ./.github/workflows/deploy.yml
    with:
      environment_name: prod
      app_version: ${{ needs.build.outputs.app_version }}
